/**
 * SPA Shell with per-article meta injection.
 *
 * Detail URLs (/nhan-dinh/<slug>, /tin-bong-da/<slug>, etc.) hit by a real
 * browser used to fall through nginx's try_files to /<hub>.html (the
 * static hub shell), so the browser tab + share preview always saw the
 * hub-level <title> ("Nhận Định & Phân Tích Bóng Đá …") instead of the
 * specific match.
 *
 * Bots already get the full-content SSR via /ssr-proxy → seoPages.js etc.
 * For browsers we don't want to send back rendered article HTML (would
 * break SPA), so this route reads the built index.html, swaps the meta
 * tags for the article-specific values, and returns it. The React mount
 * + script tags survive untouched, so the SPA hydrates exactly as before.
 *
 * Nginx pairs each detail location with a non-bot rewrite to /spa-shell:
 *   if ($is_bot) { rewrite ^ /ssr-proxy$uri?$args? last; }
 *   rewrite ^ /spa-shell$uri?$args? last;
 */

const express = require('express');
const fs = require('fs');
const path = require('path');
const router = express.Router();

const SITE_URL = process.env.SITE_URL || 'https://scoreline.io';
const SoiKeoArticle = require('../models/SoiKeoArticle');
const Article = require('../models/Article');
const AutoArticle = require('../models/AutoArticle');

// ─── Template loading ─────────────────────────────────────────────────
// index.html is generated by Vite per build; cache it once and rely on
// pm2 reload to pick up new builds. If it ever can't be read (e.g. local
// dev without a build), fall back to a minimal shell so the route never
// 500s — meta is still correct.
let _cachedTemplate = null;
let _cachedTemplateMtime = 0;
const TEMPLATE_PATHS = [
  process.env.SPA_INDEX_PATH,
  '/var/www/scoreline.io/build/index.html',
  path.join(__dirname, '..', 'public', 'index.html'),
].filter(Boolean);

function loadTemplate() {
  for (const p of TEMPLATE_PATHS) {
    try {
      const stat = fs.statSync(p);
      if (_cachedTemplate && _cachedTemplateMtime === stat.mtimeMs) return _cachedTemplate;
      _cachedTemplate = fs.readFileSync(p, 'utf-8');
      _cachedTemplateMtime = stat.mtimeMs;
      return _cachedTemplate;
    } catch (e) { /* try next */ }
  }
  return `<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><title>ScoreLine</title><meta name="description" content="ScoreLine"><link rel="canonical" href="${SITE_URL}"></head><body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>`;
}

function escapeAttr(str) {
  if (str == null) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

// Replace a meta/link tag with a new attribute, preserving the open/close
// shape from the template. Each regex looks for the *first* matching tag
// and swaps the value; if the tag doesn't exist it's a no-op (the static
// template controls which tags ship).
function replaceTag(html, regex, replacement) {
  return html.replace(regex, replacement);
}

function injectMeta(html, { title, description, canonical, ogImage, ogType }) {
  const t = escapeAttr(title);
  const d = escapeAttr(description);
  const c = escapeAttr(canonical);
  const img = escapeAttr(ogImage);
  const type = escapeAttr(ogType || 'article');

  // Use [^>]* after the property/name match so tags carrying extra attrs
  // (e.g. <meta property="og:url" content="..." id="og-url" />) still get
  // matched and replaced. Without this, index.html's id-bearing OG tags
  // were left intact and the canonical/og:url pointed to the homepage.
  html = replaceTag(html, /<title>[^<]*<\/title>/i, `<title>${t}</title>`);
  html = replaceTag(html, /<meta\s+name=["']description["'][^>]*>/i,
    `<meta name="description" content="${d}" />`);
  html = replaceTag(html, /<link\s+rel=["']canonical["'][^>]*>/i,
    `<link rel="canonical" href="${c}" />`);
  html = replaceTag(html, /<link\s+rel=["']alternate["']\s+hreflang=["']vi["'][^>]*>/i,
    `<link rel="alternate" hreflang="vi" href="${c}" />`);
  html = replaceTag(html, /<link\s+rel=["']alternate["']\s+hreflang=["']x-default["'][^>]*>/i,
    `<link rel="alternate" hreflang="x-default" href="${c}" />`);
  html = replaceTag(html, /<meta\s+property=["']og:type["'][^>]*>/i,
    `<meta property="og:type" content="${type}" />`);
  html = replaceTag(html, /<meta\s+property=["']og:url["'][^>]*>/i,
    `<meta property="og:url" content="${c}" />`);
  html = replaceTag(html, /<meta\s+property=["']og:title["'][^>]*>/i,
    `<meta property="og:title" content="${t}" />`);
  html = replaceTag(html, /<meta\s+property=["']og:description["'][^>]*>/i,
    `<meta property="og:description" content="${d}" />`);
  html = replaceTag(html, /<meta\s+name=["']twitter:url["'][^>]*>/i,
    `<meta name="twitter:url" content="${c}" />`);
  html = replaceTag(html, /<meta\s+name=["']twitter:title["'][^>]*>/i,
    `<meta name="twitter:title" content="${t}" />`);
  html = replaceTag(html, /<meta\s+name=["']twitter:description["'][^>]*>/i,
    `<meta name="twitter:description" content="${d}" />`);
  if (img) {
    html = replaceTag(html, /<meta\s+property=["']og:image["'][^>]*>/i,
      `<meta property="og:image" content="${img}" />`);
    html = replaceTag(html, /<meta\s+name=["']twitter:image["'][^>]*>/i,
      `<meta name="twitter:image" content="${img}" />`);
  }
  return html;
}

function send(res, html) {
  res.set('Content-Type', 'text/html; charset=utf-8');
  // Edge cache 5 min, stale-while-revalidate 1 day. Same envelope as the
  // static hub HTMLs so Cloudflare consolidates similar entries.
  res.set('Cache-Control', 'public, max-age=300, s-maxage=600, stale-while-revalidate=86400');
  res.send(html);
}

function trimDesc(s, max = 155) {
  if (!s) return '';
  const t = String(s).replace(/\s+/g, ' ').trim();
  if (t.length <= max) return t;
  // Trim on a sentence/word boundary so the snippet doesn't get cut mid-word.
  const slice = t.slice(0, max);
  const lastSpace = slice.lastIndexOf(' ');
  return (lastSpace > max * 0.7 ? slice.slice(0, lastSpace) : slice).trim() + '…';
}

// Fall back to the hub-level description ONLY if the article itself has
// nothing usable. Better than letting it fall through to the homepage.
function fallbackDesc(hubLabel) {
  return `${hubLabel} mới nhất trên ScoreLine — cập nhật trực tiếp, phân tích chi tiết.`;
}

// ─── /nhan-dinh/:slug — SoiKeoArticle ─────────────────────────────────
router.get('/spa-shell/nhan-dinh/:slug', async (req, res) => {
  try {
    const article = await SoiKeoArticle.findOne({ slug: req.params.slug, status: 'published' })
      .select('slug title excerpt metaTitle metaDescription thumbnail matchInfo')
      .lean();
    const tpl = loadTemplate();
    if (!article) {
      // Article not found — let SPA handle the 404; just don't poison meta
      // with a wrong description.
      return send(res, injectMeta(tpl, {
        title: 'Bài viết không tồn tại | ScoreLine',
        description: fallbackDesc('Nhận định bóng đá'),
        canonical: `${SITE_URL}/nhan-dinh/${req.params.slug}`,
      }));
    }
    const homeName = article.matchInfo?.homeTeam?.name || '';
    const awayName = article.matchInfo?.awayTeam?.name || '';
    const title = article.metaTitle
      || `${article.title} | ScoreLine`;
    const description = trimDesc(
      article.metaDescription
      || article.excerpt
      || (homeName && awayName
        ? `Nhận định ${homeName} vs ${awayName}: phân tích phong độ, đối đầu H2H, dự đoán tỷ số chi tiết.`
        : fallbackDesc('Nhận định bóng đá'))
    );
    const ogImage = article.thumbnail && article.thumbnail.startsWith('http')
      ? article.thumbnail
      : article.thumbnail ? `${SITE_URL}${article.thumbnail.startsWith('/') ? '' : '/'}${article.thumbnail}` : `${SITE_URL}/og-image.jpg`;
    send(res, injectMeta(tpl, {
      title,
      description,
      canonical: `${SITE_URL}/nhan-dinh/${article.slug}`,
      ogImage,
      ogType: 'article',
    }));
  } catch (err) {
    console.error('[SPA Shell] /nhan-dinh error:', err.message);
    send(res, loadTemplate());
  }
});

// ─── /tin-bong-da/:slug — Article ─────────────────────────────────────
router.get('/spa-shell/tin-bong-da/:slug', async (req, res) => {
  try {
    const article = await Article.findOne({ slug: req.params.slug, status: 'published' })
      .select('slug title description image category')
      .lean();
    const tpl = loadTemplate();
    if (!article) {
      return send(res, injectMeta(tpl, {
        title: 'Bài viết không tồn tại | ScoreLine',
        description: fallbackDesc('Tin bóng đá'),
        canonical: `${SITE_URL}/tin-bong-da/${req.params.slug}`,
      }));
    }
    const title = `${article.title} | ScoreLine`;
    const description = trimDesc(article.description || fallbackDesc('Tin bóng đá'));
    const ogImage = article.image && article.image.startsWith('http')
      ? article.image
      : article.image ? `${SITE_URL}${article.image.startsWith('/') ? '' : '/'}${article.image}` : `${SITE_URL}/og-image.jpg`;
    send(res, injectMeta(tpl, {
      title, description,
      canonical: `${SITE_URL}/tin-bong-da/${article.slug}`,
      ogImage, ogType: 'article',
    }));
  } catch (err) {
    console.error('[SPA Shell] /tin-bong-da error:', err.message);
    send(res, loadTemplate());
  }
});

// ─── /chuyen-nhuong/:slug — Article (category=transfer) ───────────────
router.get('/spa-shell/chuyen-nhuong/:slug', async (req, res) => {
  try {
    const article = await Article.findOne({ slug: req.params.slug, status: 'published' })
      .select('slug title description image').lean();
    const tpl = loadTemplate();
    if (!article) {
      return send(res, injectMeta(tpl, {
        title: 'Tin chuyển nhượng không tồn tại | ScoreLine',
        description: fallbackDesc('Tin chuyển nhượng'),
        canonical: `${SITE_URL}/chuyen-nhuong/${req.params.slug}`,
      }));
    }
    const title = `${article.title} | Tin Chuyển Nhượng | ScoreLine`;
    const description = trimDesc(article.description || fallbackDesc('Tin chuyển nhượng'));
    const ogImage = article.image && article.image.startsWith('http') ? article.image : article.image ? `${SITE_URL}${article.image.startsWith('/') ? '' : '/'}${article.image}` : `${SITE_URL}/og-image.jpg`;
    send(res, injectMeta(tpl, {
      title, description,
      canonical: `${SITE_URL}/chuyen-nhuong/${article.slug}`,
      ogImage, ogType: 'article',
    }));
  } catch (err) {
    console.error('[SPA Shell] /chuyen-nhuong error:', err.message);
    send(res, loadTemplate());
  }
});

// ─── /phan-tich/:slug — Article (category=analysis) ───────────────────
router.get('/spa-shell/phan-tich/:slug', async (req, res) => {
  try {
    const article = await Article.findOne({ slug: req.params.slug, status: 'published' })
      .select('slug title description image').lean();
    const tpl = loadTemplate();
    if (!article) {
      return send(res, injectMeta(tpl, {
        title: 'Bài phân tích không tồn tại | ScoreLine',
        description: fallbackDesc('Phân tích bóng đá chuyên sâu'),
        canonical: `${SITE_URL}/phan-tich/${req.params.slug}`,
      }));
    }
    const title = `${article.title} | Phân Tích | ScoreLine`;
    const description = trimDesc(article.description || fallbackDesc('Phân tích bóng đá'));
    const ogImage = article.image && article.image.startsWith('http') ? article.image : article.image ? `${SITE_URL}${article.image.startsWith('/') ? '' : '/'}${article.image}` : `${SITE_URL}/og-image.jpg`;
    send(res, injectMeta(tpl, {
      title, description,
      canonical: `${SITE_URL}/phan-tich/${article.slug}`,
      ogImage, ogType: 'article',
    }));
  } catch (err) {
    console.error('[SPA Shell] /phan-tich error:', err.message);
    send(res, loadTemplate());
  }
});

// ─── /preview/:slug + /doi-dau/:slug — AutoArticle ────────────────────
function autoArticleHandler(type, hubPath, hubLabel) {
  return async (req, res) => {
    try {
      const article = await AutoArticle.findOne({ slug: req.params.slug, type, status: 'published' })
        .select('slug title excerpt thumbnail matchInfo').lean();
      const tpl = loadTemplate();
      if (!article) {
        return send(res, injectMeta(tpl, {
          title: `Bài viết không tồn tại | ScoreLine`,
          description: fallbackDesc(hubLabel),
          canonical: `${SITE_URL}${hubPath}/${req.params.slug}`,
        }));
      }
      const title = `${article.title} | ScoreLine`;
      const homeName = article.matchInfo?.homeTeam?.name || '';
      const awayName = article.matchInfo?.awayTeam?.name || '';
      const description = trimDesc(
        article.excerpt
        || (homeName && awayName ? `${hubLabel}: ${homeName} vs ${awayName}. Phân tích chi tiết trên ScoreLine.` : fallbackDesc(hubLabel))
      );
      const ogImage = article.thumbnail && article.thumbnail.startsWith('http')
        ? article.thumbnail
        : article.thumbnail ? `${SITE_URL}${article.thumbnail.startsWith('/') ? '' : '/'}${article.thumbnail}` : `${SITE_URL}/og-image.jpg`;
      send(res, injectMeta(tpl, {
        title, description,
        canonical: `${SITE_URL}${hubPath}/${article.slug}`,
        ogImage, ogType: 'article',
      }));
    } catch (err) {
      console.error(`[SPA Shell] ${hubPath} error:`, err.message);
      send(res, loadTemplate());
    }
  };
}

router.get('/spa-shell/preview/:slug', autoArticleHandler('round-preview', '/preview', 'Preview vòng đấu'));
router.get('/spa-shell/doi-dau/:slug', autoArticleHandler('h2h-analysis', '/doi-dau', 'Đối đầu H2H'));

// ─── /tran-dau/:slug — match detail (no DB, parse slug) ──────────────
// Slug pattern: <home-kebab>-vs-<away-kebab>-HHhMM-ngay-DD-MM-YYYY
// All meta is derived from the slug itself; no API call → fast and won't
// fail if API-Sports is rate-limiting. SPA hydrates as usual, real match
// data + scores come in via the regular /api/matches/:id/detail call.
function parseMatchSlug(slug) {
  const m = slug.match(/^(.+?)-vs-(.+?)-(\d{2})h(\d{2})-ngay-(\d{2})-(\d{2})-(\d{4})$/);
  if (!m) return null;
  const [, homeKebab, awayKebab, hh, mi, dd, mo, yy] = m;
  const titleCase = (s) => s.replace(/-/g, ' ').replace(/\b([a-z])/g, (_, c) => c.toUpperCase());
  const homeName = titleCase(homeKebab);
  const awayName = titleCase(awayKebab);
  // Slug times are UTC; convert to Vietnam time (UTC+7) for human-readable
  // copy because that's the audience.
  const utcMs = Date.UTC(parseInt(yy, 10), parseInt(mo, 10) - 1, parseInt(dd, 10), parseInt(hh, 10), parseInt(mi, 10));
  const vnMs = utcMs + 7 * 3600 * 1000;
  const vn = new Date(vnMs);
  const vnHour = String(vn.getUTCHours()).padStart(2, '0');
  const vnMin = String(vn.getUTCMinutes()).padStart(2, '0');
  const vnDay = String(vn.getUTCDate()).padStart(2, '0');
  const vnMon = String(vn.getUTCMonth() + 1).padStart(2, '0');
  const vnYear = vn.getUTCFullYear();
  return {
    homeName, awayName,
    isoDate: new Date(utcMs).toISOString(),
    vnDateLabel: `${vnHour}h${vnMin} ngày ${vnDay}/${vnMon}/${vnYear}`,
    fullTitle: `${homeName} vs ${awayName}`,
  };
}

router.get('/spa-shell/tran-dau/:slug', async (req, res) => {
  const tpl = loadTemplate();
  const parsed = parseMatchSlug(req.params.slug);
  if (!parsed) {
    return send(res, injectMeta(tpl, {
      title: 'Chi tiết trận đấu | ScoreLine',
      description: 'Tỷ số trực tiếp, đội hình, thống kê và H2H trên ScoreLine.',
      canonical: `${SITE_URL}/tran-dau/${req.params.slug}`,
    }));
  }
  const { homeName, awayName, vnDateLabel, fullTitle } = parsed;
  const title = `${fullTitle} ${vnDateLabel} — Tỷ số, đội hình, H2H | ScoreLine`;
  const description = trimDesc(
    `${homeName} vs ${awayName} ${vnDateLabel}: tỷ số trực tiếp, đội hình ra sân, thống kê chi tiết, lịch sử đối đầu và phân tích trên ScoreLine.`
  );
  send(res, injectMeta(tpl, {
    title,
    description,
    canonical: `${SITE_URL}/tran-dau/${req.params.slug}`,
    // Per-match OG image (lazy-generated). FB/Twitter/Slack hits the
    // /og/match endpoint which composes & caches a 1200×630 PNG with
    // the two team names — replaces the site-wide og-image.jpg logo.
    ogImage: `${SITE_URL}/og/match/${req.params.slug}.png`,
    ogType: 'article',
  }));
});

module.exports = router;
